spring:
  jackson:
    serialization:
      indent-output: true
  devtools:
    restart:
      enabled: false

logging:
  level:
    root: INFO
    '[com.softgram.ecfs]': DEBUG
    '[org.springframework.web]': DEBUG
